/** @file 用户管理 - 新增用户弹窗 */
import { useState } from 'react'
import { KeyOutlined } from '@ant-design/icons'
import { Button, Form, Input, message, Modal, Select } from 'antd'
import type { RoleBrief } from '../../../services/userService'
import {
  createUser,
  generateRandomPassword,
} from '../../../services/userService'
import { handleFormSubmitError } from '../../../utils/errorHandler'

/** 新增用户表单值 */
interface CreateFormValues {
  username: string
  real_name: string
  phone?: string
  email?: string
  password: string
  role_ids?: string[]
}

interface CreateUserModalProps {
  open: boolean
  onClose: () => void
  onSuccess: () => void
  roleOptions: RoleBrief[]
}

/** 新增用户弹窗，包含表单校验、自动生成密码、创建成功提示 */
export function CreateUserModal({ open, onClose, onSuccess, roleOptions }: CreateUserModalProps) {
  const [loading, setLoading] = useState(false)
  const [autoGeneratedPw, setAutoGeneratedPw] = useState(false)
  const [form] = Form.useForm<CreateFormValues>()

  /** 提交创建用户 */
  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      setLoading(true)
      const result = await createUser({
        username: values.username,
        real_name: values.real_name,
        phone: values.phone || undefined,
        email: values.email || undefined,
        password: values.password,
        role_ids: values.role_ids,
      })
      onClose()
      message.success('用户创建成功')

      // 如果使用了自动生成密码，弹窗展示
      if (autoGeneratedPw && result.generated_password) {
        Modal.success({
          title: '用户创建成功',
          content: (
            <div>
              <p>用户 <strong>{result.user.username}</strong> 已创建成功。</p>
              <p className="mt-2">
                自动生成的密码：
                <strong className="ml-1" style={{ color: 'var(--gl-primary)', userSelect: 'all' }}>
                  {result.generated_password}
                </strong>
              </p>
              <p className="mt-1" style={{ color: 'var(--gl-text-tertiary)', fontSize: 12 }}>
                请妥善保管此密码，关闭后无法再次查看。
              </p>
            </div>
          ),
          okText: '我已记录',
        })
      }

      onSuccess()
    } catch (err: unknown) {
      handleFormSubmitError(err)
    } finally {
      setLoading(false)
    }
  }

  /** 自动生成密码并填入表单 */
  const handleAutoGeneratePassword = async () => {
    try {
      const pw = await generateRandomPassword()
      form.setFieldValue('password', pw)
      setAutoGeneratedPw(true)
      message.success('已自动生成密码')
    } catch {
      message.error('生成密码失败')
    }
  }

  return (
    <Modal
      title="新增用户"
      open={open}
      onOk={handleSubmit}
      onCancel={onClose}
      confirmLoading={loading}
      okText="创建"
      cancelText="取消"
      destroyOnClose
      maskClosable={false}
      width={640}
    >
      <Form form={form} layout="vertical" className="mt-4" autoComplete="off">
        <div className="grid grid-cols-2 gap-x-4">
          <Form.Item
            name="username"
            label="用户名"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input placeholder="请输入用户名" maxLength={32} />
          </Form.Item>
          <Form.Item
            name="real_name"
            label="姓名"
            rules={[{ required: true, message: '请输入姓名' }]}
          >
            <Input placeholder="请输入姓名" maxLength={32} />
          </Form.Item>
          <Form.Item name="phone" label="手机号">
            <Input placeholder="请输入手机号" maxLength={20} />
          </Form.Item>
          <Form.Item name="email" label="邮箱">
            <Input placeholder="请输入邮箱" maxLength={64} />
          </Form.Item>
          <Form.Item
            name="password"
            label="密码"
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少6个字符' },
              { pattern: /^(?=.*[a-zA-Z])(?=.*\d)/, message: '密码必须包含字母和数字' },
            ]}
          >
            <Input.Password
              placeholder="请输入密码"
              addonAfter={
                <Button
                  type="link"
                  size="small"
                  icon={<KeyOutlined />}
                  onClick={handleAutoGeneratePassword}
                  style={{ padding: 0, height: 'auto', fontSize: 12 }}
                >
                  自动生成
                </Button>
              }
            />
          </Form.Item>
          <Form.Item name="role_ids" label="角色">
            <Select
              mode="multiple"
              placeholder="请选择角色"
              options={roleOptions.map((r) => ({ label: r.name, value: r.id }))}
              allowClear
            />
          </Form.Item>
        </div>
      </Form>
    </Modal>
  )
}
