/** @file 用户管理 - 用户列表、新增编辑、状态管理 */
import { useCallback, useEffect, useState } from 'react'
import {
  PlusOutlined,
  ReloadOutlined,
  KeyOutlined,
  ExclamationCircleOutlined,
} from '@ant-design/icons'
import {
  Button,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import StatusBadge from '../../../components/common/StatusBadge'
import { getRoles, type RoleItem } from '../../../services/roleService'
import {
  createUser,
  deleteUser,
  generateRandomPassword,
  getUsers,
  resetUserPassword,
  toggleUserStatus,
  updateUser,
  type UserItem,
} from '../../../services/userService'

/** 新增用户表单值 */
interface CreateFormValues {
  username: string
  real_name: string
  phone?: string
  email?: string
  password: string
  role_ids?: string[]
}

/** 编辑用户表单值 */
interface EditFormValues {
  real_name: string
  phone?: string
  email?: string
  role_ids?: string[]
}

/** 重置密码表单值 */
interface ResetPasswordFormValues {
  new_password: string
}

/** 状态映射：1=启用 0=禁用 */
const STATUS_MAP: Record<number, { type: 'success' | 'error'; label: string }> = {
  1: { type: 'success', label: '启用' },
  0: { type: 'error', label: '禁用' },
}

export default function UserManagePage() {
  /* ========== 列表相关状态 ========== */
  const [loading, setLoading] = useState(false)
  const [dataSource, setDataSource] = useState<UserItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [keyword, setKeyword] = useState('')
  const [statusFilter, setStatusFilter] = useState<number | undefined>(undefined)

  /* ========== 角色列表（弹窗用） ========== */
  const [roleOptions, setRoleOptions] = useState<RoleItem[]>([])

  /* ========== 新增弹窗 ========== */
  const [createOpen, setCreateOpen] = useState(false)
  const [createLoading, setCreateLoading] = useState(false)
  const [createForm] = Form.useForm<CreateFormValues>()
  const [autoGeneratedPw, setAutoGeneratedPw] = useState(false)

  /* ========== 编辑弹窗 ========== */
  const [editOpen, setEditOpen] = useState(false)
  const [editLoading, setEditLoading] = useState(false)
  const [editingUser, setEditingUser] = useState<UserItem | null>(null)
  const [editForm] = Form.useForm<EditFormValues>()

  /* ========== 重置密码弹窗 ========== */
  const [resetOpen, setResetOpen] = useState(false)
  const [resetLoading, setResetLoading] = useState(false)
  const [resettingUser, setResettingUser] = useState<UserItem | null>(null)
  const [resetForm] = Form.useForm<ResetPasswordFormValues>()

  /* ========== 加载用户列表 ========== */
  const fetchUsers = useCallback(async () => {
    setLoading(true)
    try {
      const res = await getUsers({
        page,
        page_size: pageSize,
        keyword: keyword || undefined,
        status: statusFilter,
      })
      setDataSource(res.items)
      setTotal(res.total)
    } catch {
      message.error('获取用户列表失败')
    } finally {
      setLoading(false)
    }
  }, [page, pageSize, keyword, statusFilter])

  useEffect(() => {
    fetchUsers()
  }, [fetchUsers])

  /* ========== 加载角色选项 ========== */
  const fetchRoles = useCallback(async () => {
    try {
      const roles = await getRoles()
      setRoleOptions(roles)
    } catch {
      // 角色加载失败不阻塞主流程
    }
  }, [])

  useEffect(() => {
    fetchRoles()
  }, [fetchRoles])

  /* ========== 判断是否admin用户 ========== */
  const isAdmin = (user: UserItem) => user.roles?.some(r => r.name === 'admin') ?? false

  /* ========== 新增用户 ========== */
  const handleCreate = () => {
    createForm.resetFields()
    setAutoGeneratedPw(false)
    setCreateOpen(true)
  }

  const handleCreateSubmit = async () => {
    try {
      const values = await createForm.validateFields()
      setCreateLoading(true)
      const result = await createUser({
        username: values.username,
        real_name: values.real_name,
        phone: values.phone || undefined,
        email: values.email || undefined,
        password: values.password,
        role_ids: values.role_ids,
      })
      setCreateOpen(false)
      message.success('用户创建成功')

      // 如果使用了自动生成密码，弹窗展示
      if (autoGeneratedPw && result.generated_password) {
        Modal.success({
          title: '用户创建成功',
          content: (
            <div>
              <p>用户 <strong>{result.user.username}</strong> 已创建成功。</p>
              <p className="mt-2">
                自动生成的密码：
                <strong className="ml-1" style={{ color: 'var(--gl-primary)', userSelect: 'all' }}>
                  {result.generated_password}
                </strong>
              </p>
              <p className="mt-1" style={{ color: 'var(--gl-text-tertiary)', fontSize: 12 }}>
                请妥善保管此密码，关闭后无法再次查看。
              </p>
            </div>
          ),
          okText: '我已记录',
        })
      }

      fetchUsers()
    } catch (err: unknown) {
      // 表单校验失败不提示，接口错误提示
      if (err && typeof err === 'object' && 'message' in err) {
        message.error(String((err as { message: string }).message))
      }
    } finally {
      setCreateLoading(false)
    }
  }

  /** 自动生成密码（新增弹窗） */
  const handleAutoGeneratePassword = async () => {
    try {
      const pw = await generateRandomPassword()
      createForm.setFieldValue('password', pw)
      setAutoGeneratedPw(true)
      message.success('已自动生成密码')
    } catch {
      message.error('生成密码失败')
    }
  }

  /* ========== 编辑用户 ========== */
  const handleEdit = (user: UserItem) => {
    setEditingUser(user)
    editForm.setFieldsValue({
      real_name: user.real_name,
      phone: user.phone || undefined,
      email: user.email || undefined,
      role_ids: user.roles.map((r) => r.id),
    })
    setEditOpen(true)
  }

  const handleEditSubmit = async () => {
    if (!editingUser) return
    try {
      const values = await editForm.validateFields()
      setEditLoading(true)
      await updateUser({
        id: editingUser.id,
        real_name: values.real_name,
        phone: values.phone || undefined,
        email: values.email || undefined,
        role_ids: values.role_ids,
      })
      setEditOpen(false)
      message.success('用户信息更新成功')
      fetchUsers()
    } catch (err: unknown) {
      if (err && typeof err === 'object' && 'message' in err) {
        message.error(String((err as { message: string }).message))
      }
    } finally {
      setEditLoading(false)
    }
  }

  /* ========== 删除用户 ========== */
  const handleDelete = async (user: UserItem) => {
    if (isAdmin(user)) {
      message.warning('admin用户不可删除')
      return
    }
    Modal.confirm({
      title: '确认删除',
      icon: <ExclamationCircleOutlined />,
      content: `确定要删除用户「${user.real_name || user.username}」吗？此操作不可恢复。`,
      okText: '确认删除',
      okType: 'danger',
      cancelText: '取消',
      onOk: async () => {
        try {
          await deleteUser(user.id)
          message.success('删除成功')
          fetchUsers()
        } catch {
          message.error('删除失败')
        }
      },
    })
  }

  /* ========== 切换用户状态 ========== */
  const handleToggleStatus = async (user: UserItem, newStatus: number) => {
    if (isAdmin(user)) {
      message.warning('admin用户不可禁用')
      return
    }
    try {
      await toggleUserStatus(user.id, newStatus)
      message.success(newStatus === 1 ? '已启用' : '已禁用')
      fetchUsers()
    } catch {
      message.error('状态切换失败')
    }
  }

  /* ========== 重置密码 ========== */
  const handleResetPassword = (user: UserItem) => {
    setResettingUser(user)
    resetForm.resetFields()
    setResetOpen(true)
  }

  const handleResetSubmit = async () => {
    if (!resettingUser) return
    try {
      const values = await resetForm.validateFields()
      setResetLoading(true)
      await resetUserPassword(resettingUser.id, values.new_password)
      setResetOpen(false)
      message.success('密码重置成功')
    } catch (err: unknown) {
      if (err && typeof err === 'object' && 'message' in err) {
        message.error(String((err as { message: string }).message))
      }
    } finally {
      setResetLoading(false)
    }
  }

  /** 自动生成密码（重置密码弹窗） */
  const handleResetAutoGenerate = async () => {
    try {
      const pw = await generateRandomPassword()
      resetForm.setFieldValue('new_password', pw)
      message.success('已自动生成密码')
    } catch {
      message.error('生成密码失败')
    }
  }

  /* ========== 表格列定义 ========== */
  const columns: ColumnsType<UserItem> = [
    {
      title: '用户名',
      dataIndex: 'username',
      width: 120,
      ellipsis: true,
    },
    {
      title: '姓名',
      dataIndex: 'real_name',
      width: 100,
      ellipsis: true,
    },
    {
      title: '手机号',
      dataIndex: 'phone',
      width: 130,
      ellipsis: true,
      render: (val: string) => val || '-',
    },
    {
      title: '角色',
      dataIndex: 'roles',
      width: 180,
      render: (roles: UserItem['roles']) =>
        roles.length > 0
          ? roles.map((r) => (
              <Tag key={r.id} color="blue" style={{ marginInlineEnd: 4 }}>
                {r.name}
              </Tag>
            ))
          : '-',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 80,
      align: 'center',
      render: (status: number) => {
        const cfg = STATUS_MAP[status]
        return cfg ? <StatusBadge type={cfg.type}>{cfg.label}</StatusBadge> : '-'
      },
    },
    {
      title: '最后登录',
      dataIndex: 'last_login_at',
      width: 170,
      render: (val: string | null) => val || '-',
    },
    {
      title: '创建时间',
      dataIndex: 'created_at',
      width: 170,
    },
    {
      title: '操作',
      key: 'action',
      width: 220,
      fixed: 'right',
      render: (_, record) => {
        // admin用户不显示操作按钮
        if (isAdmin(record)) return null

        const isEnabled = record.status === 1

        return (
          <Space size={0} split={<span style={{ color: 'var(--gl-border)' }}>|</span>}>
            <Button type="link" size="small" onClick={() => handleEdit(record)}>
              编辑
            </Button>
            {isEnabled && (
              <Button type="link" size="small" onClick={() => handleResetPassword(record)}>
                重置密码
              </Button>
            )}
            {isEnabled ? (
              <Popconfirm
                title="确认禁用"
                description={`确定要禁用用户「${record.real_name || record.username}」吗？`}
                onConfirm={() => handleToggleStatus(record, 0)}
                okText="确认"
                cancelText="取消"
              >
                <Button type="link" size="small" danger>
                  禁用
                </Button>
              </Popconfirm>
            ) : (
              <Popconfirm
                title="确认启用"
                description={`确定要启用用户「${record.real_name || record.username}」吗？`}
                onConfirm={() => handleToggleStatus(record, 1)}
                okText="确认"
                cancelText="取消"
              >
                <Button type="link" size="small">
                  启用
                </Button>
              </Popconfirm>
            )}
            <Button type="link" size="small" danger onClick={() => handleDelete(record)}>
              删除
            </Button>
          </Space>
        )
      },
    },
  ]

  /* ========== 渲染 ========== */
  return (
    <div className="space-y-4">
      {/* 页面头部 */}
      <div
        className="rounded-xl p-5"
        style={{ background: 'var(--gl-card-bg)', border: '1px solid var(--gl-border)' }}
      >
        <div className="flex items-center justify-between">
          <h1 className="text-[18px] font-semibold" style={{ color: 'var(--gl-text-primary)' }}>
            用户管理
          </h1>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
            新增用户
          </Button>
        </div>

        {/* 筛选区 */}
        <div className="flex items-center gap-3 mt-4">
          <Input.Search
            placeholder="搜索用户名/姓名"
            allowClear
            style={{ width: 260 }}
            onSearch={(val) => {
              setKeyword(val)
              setPage(1)
            }}
          />
          <Select
            placeholder="状态筛选"
            allowClear
            style={{ width: 140 }}
            value={statusFilter}
            onChange={(val) => {
              setStatusFilter(val)
              setPage(1)
            }}
            options={[
              { label: '启用', value: 1 },
              { label: '禁用', value: 0 },
            ]}
          />
          <Button icon={<ReloadOutlined />} onClick={fetchUsers}>
            刷新
          </Button>
        </div>
      </div>

      {/* 表格区 */}
      <div
        className="rounded-xl"
        style={{ background: 'var(--gl-card-bg)', border: '1px solid var(--gl-border)' }}
      >
        <Table<UserItem>
          rowKey="id"
          size="small"
          loading={loading}
          columns={columns}
          dataSource={dataSource}
          scroll={{ x: 1100 }}
          pagination={{
            current: page,
            pageSize,
            total,
            showSizeChanger: true,
            showQuickJumper: true,
            pageSizeOptions: ['10', '20', '50'],
            showTotal: (t) => `共 ${t} 条`,
            onChange: (p, ps) => {
              setPage(p)
              setPageSize(ps)
            },
          }}
        />
      </div>

      {/* ========== 新增用户弹窗 ========== */}
      <Modal
        title="新增用户"
        open={createOpen}
        onOk={handleCreateSubmit}
        onCancel={() => setCreateOpen(false)}
        confirmLoading={createLoading}
        okText="创建"
        cancelText="取消"
        destroyOnClose
        width={520}
      >
        <Form
          form={createForm}
          layout="vertical"
          className="mt-4"
          autoComplete="off"
        >
          <Form.Item
            name="username"
            label="用户名"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input placeholder="请输入用户名" maxLength={32} />
          </Form.Item>
          <Form.Item
            name="real_name"
            label="姓名"
            rules={[{ required: true, message: '请输入姓名' }]}
          >
            <Input placeholder="请输入姓名" maxLength={32} />
          </Form.Item>
          <Form.Item name="phone" label="手机号">
            <Input placeholder="请输入手机号" maxLength={20} />
          </Form.Item>
          <Form.Item name="email" label="邮箱">
            <Input placeholder="请输入邮箱" maxLength={64} />
          </Form.Item>
          <Form.Item
            name="password"
            label="密码"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password
              placeholder="请输入密码"
              addonAfter={
                <Button
                  type="link"
                  size="small"
                  icon={<KeyOutlined />}
                  onClick={handleAutoGeneratePassword}
                  style={{ padding: 0, height: 'auto', fontSize: 12 }}
                >
                  自动生成
                </Button>
              }
            />
          </Form.Item>
          <Form.Item name="role_ids" label="角色">
            <Select
              mode="multiple"
              placeholder="请选择角色"
              options={roleOptions.map((r) => ({ label: r.name, value: r.id }))}
              allowClear
            />
          </Form.Item>
        </Form>
      </Modal>

      {/* ========== 编辑用户弹窗 ========== */}
      <Modal
        title="编辑用户"
        open={editOpen}
        onOk={handleEditSubmit}
        onCancel={() => setEditOpen(false)}
        confirmLoading={editLoading}
        okText="保存"
        cancelText="取消"
        destroyOnClose
        width={520}
      >
        {editingUser && (
          <div className="mb-4 px-3 py-2 rounded" style={{ background: 'var(--gl-content-bg)' }}>
            <span style={{ color: 'var(--gl-text-tertiary)' }}>用户名：</span>
            <span style={{ color: 'var(--gl-text-primary)' }} className="font-medium">
              {editingUser.username}
            </span>
          </div>
        )}
        <Form
          form={editForm}
          layout="vertical"
          className="mt-4"
          autoComplete="off"
        >
          <Form.Item
            name="real_name"
            label="姓名"
            rules={[{ required: true, message: '请输入姓名' }]}
          >
            <Input placeholder="请输入姓名" maxLength={32} />
          </Form.Item>
          <Form.Item name="phone" label="手机号">
            <Input placeholder="请输入手机号" maxLength={20} />
          </Form.Item>
          <Form.Item name="email" label="邮箱">
            <Input placeholder="请输入邮箱" maxLength={64} />
          </Form.Item>
          <Form.Item name="role_ids" label="角色">
            <Select
              mode="multiple"
              placeholder="请选择角色"
              options={roleOptions.map((r) => ({ label: r.name, value: r.id }))}
              allowClear
            />
          </Form.Item>
        </Form>
      </Modal>

      {/* ========== 重置密码弹窗 ========== */}
      <Modal
        title="重置密码"
        open={resetOpen}
        onOk={handleResetSubmit}
        onCancel={() => setResetOpen(false)}
        confirmLoading={resetLoading}
        okText="确认重置"
        cancelText="取消"
        destroyOnClose
        width={440}
      >
        {resettingUser && (
          <p className="mb-4" style={{ color: 'var(--gl-text-secondary)' }}>
            为用户「<strong style={{ color: 'var(--gl-text-primary)' }}>{resettingUser.real_name || resettingUser.username}</strong>」设置新密码
          </p>
        )}
        <Form form={resetForm} layout="vertical" autoComplete="off">
          <Form.Item
            name="new_password"
            label="新密码"
            rules={[{ required: true, message: '请输入新密码' }]}
          >
            <Input.Password
              placeholder="请输入新密码"
              addonAfter={
                <Button
                  type="link"
                  size="small"
                  icon={<KeyOutlined />}
                  onClick={handleResetAutoGenerate}
                  style={{ padding: 0, height: 'auto', fontSize: 12 }}
                >
                  自动生成
                </Button>
              }
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}
